### ISSUE TITLE
Redundant text files

### ISSUE THREAD

**Issue by ddu82164** [UCSB-CS56-Projects/cs56-games-guess-the-capital#11]
There are text files in both the /cs56-games-guess-the-capital/src/edu/ucsb/cs56/S12/esterkin/ directory and the /cs56-games-guess-the-capital/src/edu/ucsb/cs56/S12/esterkin/text/ directory that are exactly the same. Only one set of text files are necessary in the code.

**Comment by yukelele** [comment]
150 points

**Comment by arda-** [comment]
approved!

**Comment by arda-** [comment]
fixed
