### ISSUE TITLE
set the end boundaries of how many questions a player can ask

### ISSUE THREAD

**Issue by yukelele** [UCSB-CS56-Projects/cs56-games-guess-the-capital#17]
for the method 'customNumQuestions()', it does not have an end boundary set up. For example, a user can accidentally request for 51 questions game in a US states game mode, but this will result a IndexOutOfBound error because there are only 50 states in the US. 

150 points
(50 points for each game mode: US states, world countries, and mixture of both)

**Comment by arda-** [comment]
approved, 100 points

**Comment by yukelele** [comment]
the commit "fixes issue #19" also fixes this issue.
