### ISSUE TITLE
inconsistent junit test result for compareAnswer() 

### ISSUE THREAD

**Issue by yukelele** [UCSB-CS56-Projects/cs56-games-guess-the-capital#21]
running the junit test for compareAnswer() will sometime result an Error and give an ArithmeticException. (may need to do 'ant test' few times in order to see the Error) 

100 points

**Comment by arda-** [comment]
W16 OK

**Comment by jalexanderqed** [comment]
More specifically, there is a division by zero occurring at Game.java:306

**Comment by jalexanderqed** [comment]
F16 OK (50 pts)

**Comment by sean-shelton** [comment]
Committed a fix for this issue, however it was done before the refactoring, so things might change.
