### ISSUE TITLE
Point system & highscore

### ISSUE THREAD

**Issue by JohnUCSB** [UCSB-CS56-Projects/cs56-games-guess-the-capital#24]
Add a point system for getting each answer correct/wrong.
Store username and points that the user earned to create a highscore chart.
300 points

**Comment by jalexanderqed** [comment]
F16 OK (200 pts)

**Comment by jalexanderqed** [comment]
This has mostly been implemented, but new high scores that should appear in the table at the end of the game do not, even though they are recorded in the file `HighScores.txt`. Please fix this.

**Comment by sean-shelton** [comment]
Finished in Fall 2017, additional work was awarded 50 points
