### ISSUE TITLE
Refactor package name and folder structure to remove quarter and user-specific elements

### ISSUE THREAD

**Issue by jalexanderqed** [UCSB-CS56-Projects/cs56-games-guess-the-capital#31]
This would normally be a simple fix. However, changing the folder structure will also require changing a number of hard-coded file paths. The fact that these hard-coded paths are spread throughout the code is itself bad practice, so resolving this issue should include placing these paths either as class-level variables or in a global configuration object.

**Comment by jalexanderqed** [comment]
F16 OK (70 pts)

**Comment by sean-shelton** [comment]
Committed a fix for this issue, however it was done before the refactoring, so things might change.
