### ISSUE TITLE
Fix the test file

### ISSUE THREAD

**Issue by tgetty** [UCSB-CS56-Projects/cs56-games-guess-the-capital#6]
#5 Fix the GameTest.java, test file doesnt have good coverage
Estimated 200 points

**Comment by PazZaitGivon** [comment]
Looks good

**Comment by yukelele** [comment]
JUnit test wasn't running properly at first because there wasn't the "lib" subdirectory that contained the "junit-4.8.2.jar" file. However, this problem was fixed when I commit "fixes issue #4"
